### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hiszpanski** [lanikai/alohartc#54]
# Weekly Milestones

## Week 0: Mar 4

- [x] [JC] Demonstrate proof-of-concept end-to-end call of AlohaRTC with Oahu

## Week 1: Mar 11

- [x] [CH] Begin refactoring of ICE code. In particular, digest and understand RFC 8445 and the existing `internal/ice/` code. Understand which goroutines and channels are involved.
- [x] [NG] Wrap up company formation documents
- [x] [JC] Minimum functional API server for local development (as a "release" on GitHub). Should be able to easily add/remove devices from the frontend (using a hard-coded CA key).
- [x] [JC] Document and automate how to bring up a local dev stack.

## Week 2: Mar 18

- [x] [CH] Complete ICE refactor (10)
- [x] [CH] Fix reconnection with multiple interfaces
- [x] [JC] Reorganize Oahu code for long-term maintainability and extensibility. Add some unit tests.

## Week 3: Mar 25

- [x] [CH] Begin adding support for multiple simultaneous viewers. May need to add support for multiple SSRCs.
- [x] [NG] Research CRM options + how to structure beta test
- [x] [JC] Begin writing CloudFormation or Terraform templates for deploying to AWS.
- [x] [JC] Bring up "test" deployment in AWS, that is expected to remain mostly stable.

## Week 4: Apr 1

- [x] [CH] Complete Multi-viewers (10)
- [x] [NG] Decide on CRM
- [x] [JC] Develop an automated deployment strategy on AWS.

## Week 5: Apr 8

- [x] [CH] Begin refactoring H.264 / media sources
    - [x] [CH] Add YUYV support
    - [x] [CH] Profile connection time, CPU usage
- [x] [NG] New website copy

## Week 6: Apr 15

- [x] [CH] Complete refactor of H.264 / media sources (10)
- [x] [NG] Refactoring website + finalize new copy

## Week 7: Apr 22

- [ ] [CH] Signaling with Oahu (5)
- [ ] [CH] Fix blackness freeze bug
- [x] [NG] FAQ, ReadMe, ToS, Privacy Policy for GitHub

## Week 8: Apr 29

- [ ] [CH] TURN support (5)
- [ ] [NG] Begin tutorial (2)
- [x] [JC] Design and implement a long-term solution for the Certificate Authority. Figure out key management on AWS.
- [ ] [JC] Implement self-service demo flow (registration via email, one-line `alohacam` installer).

## Week 9: May 6

- [ ] [CH] Production build / .deb (5)
- [ ] [NG] Tutorial wrap up (1)
- [x] [JC] Auto-scale the "test" deployment (API server, MQTT, MySQL).
- [ ] [JC] Spin up "prod" deployment on AWS.

## Week 10: May 13

- [ ] [CH,JC] Final QA (5)
- [ ] [JC] Ingest and store/process RTCP summaries from `alohacam` sessions.
- [ ] [JC] Set up monitoring and alerting (for AWS resources as well as platform usage).

## Week 11: May 20

Buffer

## Week 12: May 27

Buffer

# Icebox

TODO items that don't yet warrant a separate issue:

- [ ] RFC 5506: Reduced-size RTCP

# Integrations

Other service also use WebRTC, but with their own signaling layers. Providing interoperability with these other signaling services, if possible in a scalable way, would be a huge value-add -- customers would be able to bridge their devices with Slack, Hangouts, FaceTime, etc.

* Platforms
  
  * Google Hangouts
  * Twilio Video
* Devices
  
  * Amazon Echo Show
  * Google Home Hub + Chromecast
  * Facebook Portal
* Mobile
  
  * FaceTime
  * Android
* Apps
  
  * Slack. Enable Slack users to call an embedded device directly from Slack, perhaps with support for custom call commands (e.g. `/call 1411@formlabs.lanikailabs.com`)
  * Skype
* Automotive
  
  * Android Auto?
  * CarPlay?
  * OpenCar?
  * Tesla?
* SmartTVs
